package com.jhipster.demo.pfe.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrdreTravailClientAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrdreTravailClientAllPropertiesEquals(OrdreTravailClient expected, OrdreTravailClient actual) {
        assertOrdreTravailClientAutoGeneratedPropertiesEquals(expected, actual);
        assertOrdreTravailClientAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrdreTravailClientAllUpdatablePropertiesEquals(OrdreTravailClient expected, OrdreTravailClient actual) {
        assertOrdreTravailClientUpdatableFieldsEquals(expected, actual);
        assertOrdreTravailClientUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrdreTravailClientAutoGeneratedPropertiesEquals(OrdreTravailClient expected, OrdreTravailClient actual) {
        assertThat(expected)
            .as("Verify OrdreTravailClient auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrdreTravailClientUpdatableFieldsEquals(OrdreTravailClient expected, OrdreTravailClient actual) {
        assertThat(expected)
            .as("Verify OrdreTravailClient relevant properties")
            .satisfies(e -> assertThat(e.getFraisSession()).as("check fraisSession").isEqualTo(actual.getFraisSession()))
            .satisfies(e -> assertThat(e.getArticle()).as("check article").isEqualTo(actual.getArticle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrdreTravailClientUpdatableRelationshipsEquals(OrdreTravailClient expected, OrdreTravailClient actual) {
        assertThat(expected)
            .as("Verify OrdreTravailClient relationships")
            .satisfies(e -> assertThat(e.getWorkOrder()).as("check workOrder").isEqualTo(actual.getWorkOrder()));
    }
}
