package com.jhipster.demo.pfe.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SSTAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSSTAllPropertiesEquals(SST expected, SST actual) {
        assertSSTAutoGeneratedPropertiesEquals(expected, actual);
        assertSSTAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSSTAllUpdatablePropertiesEquals(SST expected, SST actual) {
        assertSSTUpdatableFieldsEquals(expected, actual);
        assertSSTUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSSTAutoGeneratedPropertiesEquals(SST expected, SST actual) {
        assertThat(expected)
            .as("Verify SST auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSSTUpdatableFieldsEquals(SST expected, SST actual) {
        assertThat(expected)
            .as("Verify SST relevant properties")
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSSTUpdatableRelationshipsEquals(SST expected, SST actual) {
        // empty method
    }
}
